version: '3.4'
services:
  db:
    container_name: todos_db
    image: postgres:11
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
    ports:
      - "${POSTGRES_PORT_DB}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - todos-network
  pgadmin:
    container_name: pgadmin4_todos
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@mail.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "5050:80"
    depends_on: 
      - db
    networks:
      - todos-network
networks:
  todos-network:
    driver: bridge
